name: Docker Image builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-3_10:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: '3.10'

  build-3_11:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: '3.11'

  build-3_12:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: '3.12'